version: '3.1'

services:
  mysql_tickeala:
    image: mysql:lts 
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tickeala
      MYSQL_USER: tickeala
      MYSQL_PASSWORD: tickeala
    ports:
      - "3306:3306"